kind: Cluster
apiVersion: honk.honk.ci/v1
metadata:
  name: test-cluster
spec:
  kindSpec: |
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      metadata:
        name: config
      apiServer:
        extraArgs:
          enable-admission-plugins: NodeRestriction,PodSecurityPolicy
  cpu: 500m
  memory: 1Gi