# permissions for end users to view clusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-viewer-role
rules:
- apiGroups:
  - honk.honk.ci
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - honk.honk.ci
  resources:
  - clusters/status
  verbs:
  - get
